{
    'name': 'NightPOS Printer',
    'version': '19.0.1.0.32',
    'external_dependencies': {
        'python': ['PIL', 'escpos'],
    },
    'post_init_hook': 'post_init_hook',
    'summary': 'จัดการพริ้นเตอร์ TCP/ESC-POS (เซิร์ฟเวอร์ NightPOS หรือแอป NightPOS)',
    'author': 'NightPOS',
    'category': 'Point of Sale',
    'license': 'LGPL-3',
    'depends': ['web', 'point_of_sale', 'pos_tcp_esc_printer'],
    'data': [
        'security/ir.model.access.csv',
        'views/nightpos_printer_views.xml',
        'views/nightpos_printer_views_pos.xml',
        'views/nightpos_printer_menus.xml',
        'views/res_config_settings_views.xml',
        'views/pos_config_views.xml',
        'views/pos_printer_views.xml',
        'views/nightpos_device_print_views.xml',
    ],
    'assets': {
        'web.assets_web': [
            # Prepended so it executes before any OWL/Odoo JS in the bundle.
            # Required for GeckoView 99 (Firefox 99) on Sunmi T1 (Android 6.0.1).
            ('prepend', 'nightpos_printer/static/src/js/geckoview_polyfill.js'),
        ],
        'web.assets_backend': [
            'nightpos_printer/static/src/js/nightpos_test_print_routed_stub.js',
            'nightpos_printer/static/src/js/nightpos_pos_debug.js',
            'nightpos_printer/static/src/js/device_print_router.js',
            'nightpos_printer/static/src/js/local_print_ws.js',
            'nightpos_printer/static/src/js/local_printer_trigger.js',
            'nightpos_printer/static/src/js/chrome_printer_field.js',
            'nightpos_printer/static/src/js/local_print_test_dialog.js',
            'nightpos_printer/static/src/js/local_print_test_action.js',
            'nightpos_printer/static/src/js/local_print_action.js',
            'nightpos_printer/static/src/js/device_print_test_action.js',
            'nightpos_printer/static/src/js/nightpos_printer_service.js',
            'nightpos_printer/static/src/js/nightpos_test_print_action.js',
            'nightpos_printer/static/src/xml/nightpos_printer_templates.xml',
        ],
        'point_of_sale._assets_pos': [
            'nightpos_printer/static/src/pos/pos_boot_watchdog.js',
            'nightpos_printer/static/src/pos/pos_boot_trace.js',
            'nightpos_printer/static/src/pos/pos_session_fix.js',
            'nightpos_printer/static/src/scss/pos_font_fix.scss',
            'nightpos_printer/static/src/js/nightpos_pos_debug.js',
            'nightpos_printer/static/src/js/local_print_ws.js',
            'nightpos_printer/static/src/js/local_printer_trigger.js',
            'nightpos_printer/static/src/js/device_print_router.js',
            'nightpos_printer/static/src/js/nightpos_printer_service.js',
            'nightpos_printer/static/src/pos/nightpos_escpos_printer.js',
            'nightpos_printer/static/src/pos/pos_printer_service_patch.js',
            'nightpos_printer/static/src/pos/pos_receipt_patch.js',
            'nightpos_printer/static/src/pos/device_print_config_popup.js',
            'nightpos_printer/static/src/pos/device_print_login.js',
            'nightpos_printer/static/src/xml/nightpos_printer_templates.xml',
            'nightpos_printer/static/src/xml/pos_login_screen_patch.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
